#ifndef CONSTANTS_H
#define CONSTANTS_H

#define COMMAND_LIST_ARR_SIZE 6
#define MAX_KEY_SIZE 1024
#define MAX_VALUE_SIZE (MAX_KEY_SIZE) * 2
#define MAX_LINE_SIZE (MAX_KEY_SIZE + MAX_VALUE_SIZE)

#endif
