#ifndef CONSTANTS_H
#define CONSTANTS_H

#define COMMAND_LIST_ARR_SIZE 5
#define HEADER_FORMAT_SIZE 16  /* 3 x 4 bytes + 2 x 2 bytes */
#define HEADER_SIZE 16
#define CRC32_SIZE 4
#define CRC32_FORMAT_SIZE 4
#define CRC32_OFFSET CRC32_SIZE
#define HEADER_OFFSET HEADER_SIZE
#define CRC32_HEADER_OFFSET (CRC32_OFFSET + HEADER_OFFSET)

#endif
